[id="chap-alert-note-prereq"]
= Note/Tip card, 3 alert variants and prerequisites example quickstart

.Prerequisites
* You want to see some new features condensed into one example quickstart.

ifdef::qs[]
[#description-alert-note]
Preview newly added features: Alert, note, and prerequisite sections rendered using Patternfly React Components.

[#introduction]
Welcome to this example quickstart making it easy to see some new features, which will be included in a design rework of the quickstart drawer.
endif::[]

[id="task-1_{context}",module-type="proc"]
== Prerequisites expanded, note, tip, and 3 alert variants in procedure

In this Quick Start you will preview some design changes.

.Prerequisites
* Take a look at the new design changes, including this prerequisites section.
* Also take a look at the note, tip, and 3 types of alerts renderd by PF React.

.Procedure
. Note
+
NOTE: I am a note card (triggerd by NOTE admonition in asciidoc) rendered by Patternfly React Components.
+

. Tip
+
TIP: I am a tip card (triggerd by TIP admonition in asciidoc) rendered by Patternfly React Components.
+

. Info
+
IMPORTANT: I am an info alert (triggerd by IMPORTANT admonition in asciidoc) rendered by Patternfly React Components.
+

. Warning
+
CAUTION: I am a warning alert (triggerd by CAUTION admonition in asciidoc) rendered by Patternfly React Components.
+

. Danger
+
WARNING: I am a danger alert (triggerd by WARNING admonition in asciidoc) rendered by Patternfly React Components.

.Verification
. Do you see a note and info card?
. Do you see 3 types of alerts and task-level prerequisites?


[id="proc-description-with-admonition-blocks_{context}"]
== Note, tip and 3 alert variants in task description

Note:

NOTE: If you'd like to use a service account that already has the required role, you  can skip this section.

Tip:

TIP: If you want to use a service account that already has the required role, you can skip this section.

Important:

IMPORTANT: If you want to use a service account that already has the required role, you can skip this section.

Caution:

CAUTION: If you want to use a service account that already has the required role, you can skip this section.

Warning:

WARNING: If you want to use a service account that already has the required role, you can skip this section.

.Prerequisites
* Review at description above

.Procedure
. No steps for this task

.Verification
* Did you see the sections above?

[id="task-3_{context}",module-type="proc"]
== Long procedure step with multiple paragraphs and admonitions

.Prerequisites
* None

.Procedure
. For the *Authentication method*, copy the OAuth *Token endpoint URL* to a secure location. This is the endpoint that you’ll use with your service account credentials to authenticate the connection to this {registry} instance.
+
NOTE: HTTP Basic authentication is also available for tools and libraries that don't support OAuth, but OAuth is recommended whenever possible. With HTTP Basic, you use only the service account credentials to authenticate the connection to the {registry} instance.
+
You’ll use the service account information that you saved to configure your applications to connect to your {registry} instances later when you're ready.
+
IMPORTANT: This is an important alert to test multiple amonition blocks in one list item
+
For example, if you plan to use https://github.com/edenhill/kafkacat[Kafkacat^] to interact with your Kafka instance and deserialize Avro messages using {registry}, you'll use this information to set your {registry} URL in the client environment variables.
+
To review your service account information, reset your credentials, or delete the service account, use the left navigation menu to go to the *Service Accounts* page.

.Verification
. Do you see a note section?
. Do you see an alert section and task-level prerequisites?.

[#conclusion]
Congratulations! You successfully completed the example quick start, and are now aware of the new features.

