apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: example
spec:
  conclusion: >-
    Your example **httpd-24-centos7-app** application, using the
    **quay.io/centos7/httpd-24-centos7** image, is deployed and ready.
  description: Deploy an example application from an image.
  displayName: Deploy image
  durationMinutes: 5
  introduction: >-
    ### In this example quick start, you'll deploy an existing image to
    OpenShift. For more information on writing quick starts, see our [quick
    start
    guidelines.](http://openshift.github.io/openshift-origin-design/conventions/documentation/quick-starts.html)
  tags:
    - example
    - image
    - deployment
  tasks:
    - description: |-
        ### To deploy the **httpd-24-centos7** image, follow these steps:

        ```
        This can be copied.
        ```{{copy}}


        1. Enter the developer perspective: In the main navigation menu, click
        the [dropdown menu]{{highlight tour-perspective-dropdown}} and select
        **Developer**.

          ```
          This cannot be copied.
          ```{{copy}}

        2. In the main navigation menu, click **Add.**

          
          [This can be an accordion input, followed by another]{{accordion "testing with more text"}}

        3. Using the project dropdown menu, select the project you would like to
        deploy the image in.

        4. Click the **Container Image** tile.

        5. In the **Image name from external registry** field, enter
        **quay.io/centos7/httpd-24-centos7**.

        6. Fill in the remaining image deployment details, and then click
        **Create.**


        The **Topology** view will load with your **httpd-24-centos7-app**
        application. The outer rim of the larger circle represents your
        application, and the small circle represents the deployment.
      review:
        failedTaskHelp: This task isn't verified yet. Try the task again.
        instructions: |-
          #### Verify the image was successfully deployed:
          Do you see a **httpd-24-centos7** deployment?
      summary:
        failed: Try the steps again.
        success: >-
          Great work! You deployed an example application using the
          **quay.io/centos7/httpd-24-centos7** image.
      title: Deploy an existing image from an image registry
